---
title: "Playing Around with 2022 NFL Data"
author: "Jack Miller"
output: pdf_document
---

A running R markdown looking at 2022 NFL data using the `nflfastR` package.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```

## Loading packages and data

```{r Load packages + data, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(nflreadr)
library(nflplotR)
stats2022 <- load_player_stats(2022) %>% 
  mutate(year = 2022)
pbp2022 <- load_pbp(2022) %>% 
  mutate(year = 2022)
stats2021 <- load_player_stats(2021) %>% 
  mutate(year = 2021)
pbp2021 <- load_pbp(2021) %>% 
  mutate(year = 2021)
stats_21_22 <- rbind(stats2022, stats2021)
pbp_21_22 <- rbind(pbp2022, pbp2021)
```

# 2022 NFL Data Exploration

```{r 2022 Week 12 Target/Carries Leaders, warning=FALSE, message=FALSE}
week12_carry_leaders <- stats2022 %>% 
  filter(week == 12) %>% 
  arrange(desc(carries)) %>% 
  select(player_name, position, carries, rushing_yards, rushing_epa, rushing_tds)
week12_rb_target_leaders <- stats2022 %>% 
  filter(week == 12,  position == "RB") %>% 
  arrange(desc(targets)) %>% 
  select(player_name, position, targets, receptions, receiving_epa, target_share)
week12_wr_target_leaders <- stats2022 %>% 
  filter(week == 12,  position == "WR") %>% 
  arrange(desc(targets)) %>% 
  select(player_name, position, targets, receptions, receiving_epa, target_share)
week12_te_target_leaders <- stats2022 %>% 
  filter(week == 12,  position == "TE") %>% 
  arrange(desc(targets), desc(target_share)) %>% 
  select(player_name, position, targets, receptions, receiving_epa, target_share)
head(week12_carry_leaders, 20)
head(week12_rb_target_leaders, 20)
head(week12_wr_target_leaders, 20)
head(week12_te_target_leaders, 20)
```

```{r Week 12 Positional Leaders, warning=FALSE, message=FALSE}
week12_passing_leaders <- stats2022 %>% 
  filter(week == 12, position == "QB") %>% 
  arrange(desc(passing_epa)) %>% 
  select(player_name, position, passing_epa, passing_yards, completions, passing_tds)
week12_rushing_leaders <- stats2022 %>% 
  filter(week == 12, position == "RB") %>% 
  arrange(desc(rushing_epa)) %>% 
  select(player_name, position, rushing_epa, rushing_yards, carries, rushing_tds)
week12_receiving_leaders <- stats2022 %>% 
  filter(week == 12) %>% 
  arrange(desc(receiving_epa)) %>% 
  select(player_name, position, receiving_epa, receiving_yards, targets, receptions, receiving_tds)
head(week12_passing_leaders, 20)
head(week12_rushing_leaders, 20)
head(week12_receiving_leaders, 20)
```

```{r Week 12}
week12_pbp <- pbp2022 %>% 
  filter(week == 12) %>% 
  arrange(desc(yards_gained)) %>% 
  select(yards_gained, posteam)
head(week12_pbp, 10)
```

```{r}
stats2022 %>% filter(week == 12 & targets > 3 & position == "TE") %>% 
  ggplot(aes(x = receiving_epa, y = receptions, label = player_name)) +
  geom_text(check_overlap = TRUE) + 
  labs(title = "TE Receiving EPA ")
```

```{r}
stats2022 %>% filter(week == 12 & targets > 3 & position == "WR") %>% 
  ggplot(aes(x = receiving_epa, y = receptions, label = player_name)) +
  geom_text(check_overlap = TRUE) + 
  labs(title = "WR Receiving EPA ")
```

```{r}
stats2022 %>% filter(week == 12 & carries > 10 & position == "RB") %>% 
  ggplot(aes(x = rushing_epa, y = carries, label = player_name)) +
  geom_text(check_overlap = TRUE) + 
  labs(title = "RB Rushing EPA ")
```

# Mean Pass on Neutral Plays

```{r}
pbp_rp <- pbp2022 %>%
  filter(rush == 1 | pass == 1, !is.na(epa))
schotty <- pbp_rp %>% 
  filter(wp > .20 & wp < .80 & down <= 2 & qtr <= 2 & 
           half_seconds_remaining > 120) %>%
    group_by(posteam) %>%
    summarize(mean_pass = mean(pass), plays = n()) %>%
    arrange(-mean_pass)
ggplot(schotty, aes(x=reorder(posteam,-mean_pass), y=mean_pass)) +
        geom_text(aes(label=posteam))
```

# EPA Exploration

```{r}
pbp2022 %>% 
  filter(!is.na(epa)) %>% 
  select(posteam, yardline_100, game_seconds_remaining, down, ydstogo, yards_gained, play_type, score_differential, ep, epa, )
```

# 2017-2021 QB EPA Example

```{r example QB epa}
pbp <- load_pbp(2017:2021)
qbs <- pbp %>%
  filter(season_type == "REG", !is.na(epa)) %>%
  group_by(id, name) %>%
  summarize(
    epa = mean(qb_epa),
    cpoe = mean(cpoe, na.rm = T),
    n_dropbacks = sum(pass),
    n_plays = n(),
    team = last(posteam)
  ) %>%
  ungroup() %>%
  filter(n_dropbacks > 100 & n_plays > 1000) %>% 
  left_join(load_teams(), by = c('team' = 'team_abbr'))
```

# 2022 NFL QB EPA

```{r}
qb_2022 <- pbp2022 %>% 
  filter(!is.na(epa)) %>% 
  group_by(id, name) %>%
  summarize(
    epa = mean(qb_epa),
    cpoe = mean(cpoe, na.rm = T),
    n_dropbacks = sum(pass),
    n_plays = n(),
    team = last(posteam)
  ) %>%
  ungroup() %>%
  filter(n_dropbacks > 10 & n_plays > 100) %>% 
  left_join(load_teams(), by = c('team' = 'team_abbr'))

qb_2022 %>%
  ggplot(aes(x = cpoe, y = epa)) +
  geom_hline(yintercept = mean(qb_2022$epa), color = "red", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept =  mean(qb_2022$cpoe), color = "red", linetype = "dashed", alpha=0.5) +
  geom_point(color = qb_2022$team_color, cex=qb_2022$n_plays / 50, alpha = .6) +
  geom_text_repel(aes(label=name)) +
  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+
  labs(x = "Completion % above expected (CPOE)",
       y = "EPA per play (passes, rushes, and penalties)",
       title = "Quarterback Efficiency, 2022 Season",
       caption = "Data: @nflfastR") +
  theme_bw() +
  theme(
    plot.title = element_text(size = 14, hjust = 0.5, face = "bold")
  ) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))
```


# Week 11 Jalen Hurts

```{r}
jalen_epa <- pbp2022 %>% 
  filter(name == "J.Hurts" & play_type == c("run", "pass")) %>% 
  group_by(week, play_type) %>% 
  summarise(total_epa = sum(epa))
jalen_epa %>% 
  filter(play_type == "run") %>% 
  ggplot(aes(x = week, y = total_epa)) +
  geom_point()
```

```{r}
jalen_epa %>% 
  filter(play_type == "pass") %>% 
  arrange(desc(total_epa))
```

# Week 11 TE EPA

```{r}
stats2022 %>% filter(week == 12 & targets > 3 & position == "TE") %>% 
  ggplot(aes(x = receiving_epa, y = receptions, label = player_name)) +
  geom_text(check_overlap = TRUE) + 
  labs(title = "TE Receiving EPA ")
```

# 4th Down 

``` {r } 
team_4th <- pbp2022 %>% 
  filter(down == 4 & (play_type == "run" | play_type == "pass")) %>% 
  filter(wp > 0.02 & wp < 0.98) %>% 
  group_by(posteam) %>% 
  summarise(avg_yds_to_go = mean(ydstogo),
            avg_field_pos = mean(yardline_100),
            count = n(),
            success_rate = sum(fourth_down_converted) / count,
            avg_gained = sum(yards_gained) / count) %>% 
  arrange(desc(success_rate))
team_4th
```

```{r}
ggplot(team_4th, aes(x = success_rate, y = avg_gained)) +
  geom_nfl_logos(aes(team_abbr = posteam), width = team_4th$count / 300, alpha = 0.75) +
  geom_hline(yintercept = mean(team_4th$avg_gained), color = "red", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept =  mean(team_4th$success_rate), color = "red", linetype = "dashed", alpha=0.5) +
  labs(title = "4th Down Success vs. Average Yards Gained on 4th Down",
       subtitle = "2022 NFL Games, WP between 0.02 and 0.98, Logo Size = # Qualifying Plays",
       y = "Average Yards Gained", x = "4th Down Success Rate", caption = "Jack Miller | data: @nflfastR")
ggplot(team_4th, aes(x = success_rate, y = avg_yds_to_go)) +
  geom_nfl_logos(aes(team_abbr = posteam), width = team_4th$count / 300, alpha = 0.75) +
  geom_hline(yintercept = mean(team_4th$avg_yds_to_go), color = "red", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept =  mean(team_4th$success_rate), color = "red", linetype = "dashed", alpha=0.5) +
  labs(title = "4th Down Success vs. Average Yards To Go on 4th Down",
       subtitle = "2022 NFL Games, WP between 0.02 and 0.98, Logo Size = # Qualifying Plays",
       y = "Average Yards To Go", x = "4th Down Success Rate", caption = "Jack Miller | data: @nflfastR")
```

# 2022 Offense vs Defense EPA (Through Week 12)

```{r}
pbp_2022_epa <- pbp2022 %>%
  filter(!is.na(posteam) & (rush == 1 | pass == 1)) %>% 
  filter(wp > 0.02 & wp < 0.98)
offense_2022 <- pbp_2022_epa %>%
  dplyr::group_by(team = posteam) %>%
  dplyr::summarise(off_epa = mean(epa, na.rm = TRUE))
defense_2022 <- pbp_2022_epa %>%
  dplyr::group_by(team = defteam) %>%
  dplyr::summarise(def_epa = mean(epa, na.rm = TRUE))
offense_2022 %>%
  dplyr::inner_join(defense_2022, by = "team") %>%
  ggplot2::ggplot(aes(x = off_epa, y = def_epa)) +
  ggplot2::geom_abline(slope = -1.5, intercept = (4:-3)/10, alpha = .2) +
  nflplotR::geom_mean_lines(aes(h_var = off_epa, v_var = def_epa)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.05, alpha = 0.7) +
  labs(
    x = "Offense EPA/play",
    y = "Defense EPA/play",
    caption = "Jack Miller | Data: @nflfastR") +
  ggtitle(expression(atop("2022 NFL Offensive and Defensive EPA per Play", 
                          atop(italic("Win prob 2-98%; Downs: 1-4; Qtrs: all"), "")))) +
  theme_bw() +
  theme(
    plot.title = ggplot2::element_text(size = 16, hjust = 0.5, face = "bold")
  ) +
  scale_y_reverse()
```

# 2022 Week 12 Team EPA

```{r}
pbp_2022_w12_epa <- pbp2022 %>%
  filter(week == 12) %>%
  filter(!is.na(posteam) & (rush == 1 | pass == 1)) %>% 
  filter(wp > 0.02 & wp < 0.98)
offense_w12 <- pbp_2022_w12_epa %>%
  group_by(team = posteam) %>%
  summarise(off_epa = mean(epa, na.rm = TRUE))
defense_w12 <- pbp_2022_epa %>%
  group_by(team = defteam) %>%
  summarise(def_epa = mean(epa, na.rm = TRUE))
offense_w12 %>%
  inner_join(defense_w12, by = "team") %>%
  ggplot(aes(x = off_epa, y = def_epa)) +
  geom_mean_lines(aes(h_var = off_epa, v_var = def_epa)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.05, alpha = 0.7) +
  labs(
    x = "Offense EPA/play",
    y = "Defense EPA/play",
    caption = "Jack Miller | Data: @nflfastR") +
  ggtitle(expression(atop("2022 Week 12 NFL Offensive and Defensive EPA per Play", 
                          atop(italic("Win prob 2-98%; Downs: 1-4; Qtrs: all"), "")))) +
  theme_bw() +
  theme(
    plot.title = ggplot2::element_text(size = 16, hjust = 0.5, face = "bold")
  ) +
  scale_y_reverse()
```


